version: '3.7'

services:
  app:
    image: alpine
    command: ['tail', '-f', '/dev/null']
    networks:
      - project-b-network

networks:
  project-b-network:
    external: true
    name: project-b_default